namespace :guides do

  desc 'Generate guides (for authors), use ONLY=foo to process just "foo.md"'
  task :generate => 'generate:html'

  namespace :generate do

    desc "Generate HTML guides"
    task :html do
      ENV["WARN_BROKEN_LINKS"] = "1" # authors can't disable this
      ruby "rails_guides.rb"
    end

    #############################################
    # Tasks written by ROR Lab.
    #############################################
    namespace :html do
      desc "Generate HTML guides from source/ko (for ROR Lab.)"
      task :ko do
        ENV["WARN_BROKEN_LINKS"] = "1" # authors can't disable this
        ENV["GUIDES_LANGUAGE"] = "ko"
        ENV["EDGE"] = "1"
        # ENV["ALL"] = "1"
        ruby "rails_guides.rb"
      end
      namespace :ko do
        desc "Publish the guides to shared/rg (for ROR Lab.)"
        task :publish => :ko do
          require 'rake/contrib/sshpublisher'
          mkdir_p 'pkg'
          `tar -czf pkg/guides_ko.gz output/ko`
          Rake::SshFilePublisher.new("deployer@rorlab.org", "/home/deployer/apps/rorlab/shared", "pkg", "guides_ko.gz").upload
          `ssh deployer@rorlab.org 'cd /home/deployer/apps/rorlab/shared/ && tar -xvzf guides_ko.gz && rm -rf rg && mkdir rg && mv -f output/ko/* rg && rm -rf output && rm guides_ko.gz'`
        end
      end
    end
    namespace :kindle do
      desc "Generate .mobi file. The kindlegen executable must be in your PATH. You can get it for free from http://www.amazon.com/kindlepublishing"
      task :ko do
        unless `kindlerb -v 2> /dev/null` =~ /kindlerb 0.1.1/
          abort "Please install kindlegen on your path and `gem install kindlerb`"
        end
        unless `convert` =~ /convert/
          abort "Please install ImageMagick`"
        end
        ENV['KINDLE'] = '1'
        Rake::Task['guides:generate:html:ko'].invoke
      end
    end
    #############################################

    desc "Generate .mobi file. The kindlegen executable must be in your PATH. You can get it for free from http://www.amazon.com/kindlepublishing"
    task :kindle do
      unless `kindlerb -v 2> /dev/null` =~ /kindlerb 0.1.1/
        abort "Please `gem install kindlerb` and make sure you have `kindlegen` in your PATH"
      end
      unless `convert` =~ /convert/
        abort "Please install ImageMagick`"
      end
      ENV['KINDLE'] = '1'
      Rake::Task['guides:generate:html'].invoke
    end
  end

  # Validate guides -------------------------------------------------------------------------
  desc 'Validate guides, use ONLY=foo to process just "foo.html"'
  task :validate do
    ruby "w3c_validator.rb"
  end

  desc "Show help"
  task :help do
    puts <<-help

Guides are taken from the source directory, and the result goes into the
output directory. Assets are stored under files, and copied to output/files as
part of the generation process.

You can generate HTML, Kindle or both formats using the `guides:generate` task.

All of these processes are handled via rake tasks, here's a full list of them:

#{%x[rake -T]}
Some arguments may be passed via environment variables:

  WARNINGS=1
    Internal links (anchors) are checked, also detects duplicated IDs.

  ALL=1
    Force generation of all guides.

  ONLY=name
    Useful if you want to generate only one or a set of guides.

    Generate only association_basics.html:
      ONLY=assoc

    Separate many using commas:
      ONLY=assoc,migrations

  GUIDES_LANGUAGE
    Use it when you want to generate translated guides in
    source/<GUIDES_LANGUAGE> folder (such as source/es)

  EDGE=1
    Indicate generated guides should be marked as edge.

Examples:
  $ rake guides:generate ALL=1
  $ rake guides:generate EDGE=1
  $ rake guides:generate:kindle EDGE=1
  $ rake guides:generate GUIDES_LANGUAGE=es
    help
  end
end

task :default => 'guides:help'
